import FibonacciRibbonKernel.IntegerPowerLogCoefficient
import FibonacciRibbonKernel.CatalanAsymptotic
import Mathlib.Data.Nat.Choose.Central

namespace FibonacciRibbonKernel

open PowerSeries
open Filter Asymptotics
open scoped BigOperators

/-!
# Coefficients of the half-integral power model

The remaining regular-singular parity is generated by
`(1-scale*X)^(order-1/2)`.  We first establish the exact coefficient ratio for
generalized binomial coefficients and identify the order-zero carrier with the
central-binomial series.
-/

theorem ringChoose_succ_right_ratio (parameter : ℝ) (index : ℕ) :
    (index + 1 : ℝ) * Ring.choose parameter (index + 1) =
      (parameter - index) * Ring.choose parameter index := by
  have hsucc := Ring.descPochhammer_eq_factorial_smul_choose
    (R := ℝ) parameter (index + 1)
  have hprev := Ring.descPochhammer_eq_factorial_smul_choose
    (R := ℝ) parameter index
  simp only [nsmul_eq_mul] at hsucc hprev
  have hpoch :
      (descPochhammer ℤ (index + 1)).smeval parameter =
        (descPochhammer ℤ index).smeval parameter *
          (parameter - index) := by
    rw [descPochhammer_succ_right]
    simp [Polynomial.smeval_mul, Polynomial.smeval_sub,
      Polynomial.smeval_X, Polynomial.smeval_natCast]
  rw [hpoch, hprev, Nat.factorial_succ] at hsucc
  push_cast at hsucc
  have hfactorial : (index.factorial : ℝ) ≠ 0 := by positivity
  calc
    (index + 1 : ℝ) * Ring.choose parameter (index + 1) =
        ((index + 1 : ℝ) * (index.factorial : ℝ) *
          Ring.choose parameter (index + 1)) /
            (index.factorial : ℝ) := by field_simp
    _ = ((index.factorial : ℝ) * Ring.choose parameter index *
          (parameter - index)) / (index.factorial : ℝ) := by
      rw [← hsucc]
    _ = (parameter - index) * Ring.choose parameter index := by
      field_simp [hfactorial]

theorem ringChoose_top_succ_ratio (parameter : ℝ) (index : ℕ) :
    (parameter + 1 - index) * Ring.choose (parameter + 1) index =
      (parameter + 1) * Ring.choose parameter index := by
  cases index with
  | zero => simp
  | succ index =>
      rw [Ring.choose_succ_succ]
      have hratio := ringChoose_succ_right_ratio parameter index
      push_cast at hratio ⊢
      calc
        (parameter + 1 - (index + 1)) *
            (Ring.choose parameter index +
              Ring.choose parameter (index + 1)) =
          (parameter - index) * Ring.choose parameter index +
            (parameter - index) * Ring.choose parameter (index + 1) := by
              ring
        _ = (index + 1) * Ring.choose parameter (index + 1) +
            (parameter - index) * Ring.choose parameter (index + 1) := by
              rw [← hratio]
        _ = (parameter + 1) * Ring.choose parameter (index + 1) := by
              ring

theorem choose_neg_half_eq_central (index : ℕ) :
    Ring.choose (-(1 / 2 : ℝ)) index =
      (-1 : ℝ) ^ index * (Nat.centralBinom index : ℝ) /
        (4 : ℝ) ^ index := by
  induction index with
  | zero => simp
  | succ index ih =>
      have hchoose := ringChoose_succ_right_ratio (-(1 / 2 : ℝ)) index
      have hcentralNat := Nat.succ_mul_centralBinom_succ index
      have hcentral :
          (index + 1 : ℝ) * (Nat.centralBinom (index + 1) : ℝ) =
            2 * (2 * index + 1 : ℝ) * (Nat.centralBinom index : ℝ) := by
        exact_mod_cast hcentralNat
      have hindex : (index + 1 : ℝ) ≠ 0 := by positivity
      have hfour : (4 : ℝ) ^ index ≠ 0 := by positivity
      rw [ih] at hchoose
      have hchooseSolve :
          Ring.choose (-(1 / 2 : ℝ)) (index + 1) =
            (-(1 / 2 : ℝ) - index) *
                ((-1 : ℝ) ^ index * (Nat.centralBinom index : ℝ) /
                  (4 : ℝ) ^ index) /
              (index + 1 : ℝ) := by
        rw [eq_div_iff hindex]
        simpa [mul_comm] using hchoose
      have hcentralSolve :
          (Nat.centralBinom (index + 1) : ℝ) =
            (2 * (2 * index + 1 : ℝ) *
              (Nat.centralBinom index : ℝ)) / (index + 1 : ℝ) := by
        rw [eq_div_iff hindex]
        simpa [mul_comm] using hcentral
      rw [hchooseSolve, hcentralSolve, pow_succ, pow_succ]
      field_simp [hindex, hfour]
      ring

theorem halfPowerSeries_zero_coeff (scale : ℝ) (index : ℕ) :
    PowerSeries.coeff index (halfPowerSeries 0 scale) =
      scale ^ index * (Nat.centralBinom index : ℝ) / (4 : ℝ) ^ index := by
  rw [halfPowerSeries_coeff]
  norm_num
  rw [choose_neg_half_eq_central]
  have hsign : (-1 : ℝ) ^ index * (-1 : ℝ) ^ index = 1 := by
    rw [← mul_pow]
    norm_num
  have hfour : (4 : ℝ) ^ index ≠ 0 := by positivity
  field_simp [hfour]
  rw [neg_pow]
  calc
    (-1 : ℝ) ^ index * scale ^ index * (-1 : ℝ) ^ index *
        (Nat.centralBinom index : ℝ) =
      ((-1 : ℝ) ^ index * (-1 : ℝ) ^ index) *
        (scale ^ index * (Nat.centralBinom index : ℝ)) := by ring
    _ = (Nat.centralBinom index : ℝ) * scale ^ index := by
      rw [hsign]
      ring

/-- Product of the odd numerator factors generated by integral shifts of the
half-power exponent. -/
noncomputable def halfOddNumerator (order : ℕ) : ℝ :=
  ∏ shift ∈ Finset.range order, ((2 * shift + 1 : ℕ) : ℝ)

/-- Product of the odd denominator factors in the shifted half-power
coefficient. -/
noncomputable def halfOddDenominator (order index : ℕ) : ℝ :=
  ∏ shift ∈ Finset.range order,
    (((2 * index : ℕ) : ℝ) - ((2 * shift + 1 : ℕ) : ℝ))

theorem halfOddNumerator_succ (order : ℕ) :
    halfOddNumerator (order + 1) =
      halfOddNumerator order * (2 * order + 1 : ℕ) := by
  simp [halfOddNumerator, Finset.prod_range_succ]

theorem halfOddDenominator_succ (order index : ℕ) :
    halfOddDenominator (order + 1) index =
      halfOddDenominator order index *
        (((2 * index : ℕ) : ℝ) - (2 * order + 1 : ℕ)) := by
  simp [halfOddDenominator, Finset.prod_range_succ]

theorem halfOddDenominator_ne_zero (order index : ℕ) :
    halfOddDenominator order index ≠ 0 := by
  unfold halfOddDenominator
  apply Finset.prod_ne_zero_iff.mpr
  intro shift _hshift hzero
  have heq : ((2 * index : ℕ) : ℝ) = (2 * shift + 1 : ℕ) :=
    sub_eq_zero.mp hzero
  have heqNat : 2 * index = 2 * shift + 1 := by exact_mod_cast heq
  omega

theorem choose_shifted_neg_half_closed (order index : ℕ) :
    Ring.choose ((order : ℝ) - 1 / 2) index =
      (-1 : ℝ) ^ order * Ring.choose (-(1 / 2 : ℝ)) index *
        halfOddNumerator order / halfOddDenominator order index := by
  induction order with
  | zero =>
      simp [halfOddNumerator, halfOddDenominator]
  | succ order ih =>
      let parameter : ℝ := (order : ℝ) - 1 / 2
      have hshift : ((order + 1 : ℕ) : ℝ) - 1 / 2 = parameter + 1 := by
        dsimp only [parameter]
        push_cast
        ring
      have hratio := ringChoose_top_succ_ratio parameter index
      have hfactor :
          parameter + 1 - (index : ℝ) =
            -(((2 * index : ℕ) : ℝ) - (2 * order + 1 : ℕ)) / 2 := by
        dsimp only [parameter]
        push_cast
        ring
      have hfactorNe :
          (((2 * index : ℕ) : ℝ) - (2 * order + 1 : ℕ)) ≠ 0 := by
        intro hzero
        have heq : ((2 * index : ℕ) : ℝ) = (2 * order + 1 : ℕ) :=
          sub_eq_zero.mp hzero
        have heqNat : 2 * index = 2 * order + 1 := by exact_mod_cast heq
        omega
      have hleftNe : parameter + 1 - (index : ℝ) ≠ 0 := by
        rw [hfactor]
        exact div_ne_zero (neg_ne_zero.mpr hfactorNe) (by norm_num)
      have hsolve :
          Ring.choose (parameter + 1) index =
            (parameter + 1) * Ring.choose parameter index /
              (parameter + 1 - (index : ℝ)) := by
        rw [eq_div_iff hleftNe]
        simpa [mul_comm] using hratio
      have hstep :
          Ring.choose (parameter + 1) index =
            -((2 * order + 1 : ℕ) : ℝ) /
                (((2 * index : ℕ) : ℝ) - (2 * order + 1 : ℕ)) *
              Ring.choose parameter index := by
        rw [hsolve, hfactor]
        dsimp only [parameter]
        push_cast
        field_simp [hfactorNe]
        ring
      rw [hshift, hstep, ih, halfOddNumerator_succ,
        halfOddDenominator_succ, pow_succ]
      have hdenom := halfOddDenominator_ne_zero order index
      field_simp [hfactorNe, hdenom]

noncomputable def halfPowerClosedCoefficient
    (order : ℕ) (scale : ℝ) (index : ℕ) : ℝ :=
  (-1 : ℝ) ^ order * scale ^ index *
      (Nat.centralBinom index : ℝ) / (4 : ℝ) ^ index *
    halfOddNumerator order / halfOddDenominator order index

theorem halfPowerSeries_coeff_closed
    (order : ℕ) (scale : ℝ) (index : ℕ) :
    PowerSeries.coeff index (halfPowerSeries order scale) =
      halfPowerClosedCoefficient order scale index := by
  rw [halfPowerSeries_coeff, choose_shifted_neg_half_closed,
    choose_neg_half_eq_central]
  unfold halfPowerClosedCoefficient
  have hsign : (-1 : ℝ) ^ (index * 2) = 1 := by
    rw [Nat.mul_comm, pow_mul]
    norm_num
  have hsignSq : ((-1 : ℝ) ^ index) ^ 2 = 1 := by
    simpa [pow_mul] using hsign
  have hfour : (4 : ℝ) ^ index ≠ 0 := by positivity
  have hdenom := halfOddDenominator_ne_zero order index
  rw [neg_pow]
  field_simp [hfour, hdenom]
  rw [hsignSq]
  ring

noncomputable def halfOddDenominatorLeading
    (order index : ℕ) : ℝ :=
  (2 * (index : ℝ)) ^ order

theorem besselLinearFactor_isEquivalent
    (shift : ℕ) :
    (fun index : ℕ =>
      (2 * (index : ℝ)) - (2 * shift + 1 : ℕ)) ~[atTop]
      (fun index : ℕ => 2 * (index : ℝ)) := by
  have hne : ∀ᶠ index : ℕ in atTop, (2 : ℝ) * index ≠ 0 := by
    filter_upwards [eventually_ne_atTop 0] with index hindex
    positivity
  rw [isEquivalent_iff_tendsto_one hne]
  have hlimit := tendsto_add_mul_div_add_mul_atTop_nhds
    (-(2 * shift + 1 : ℕ) : ℝ) 0 2 (by norm_num : (2 : ℝ) ≠ 0)
  change Tendsto (fun index : ℕ =>
    ((2 : ℝ) * index - (2 * shift + 1 : ℕ)) /
      ((2 : ℝ) * index)) atTop (nhds 1)
  convert hlimit using 1
  · funext index
    push_cast
    ring
  · norm_num

theorem halfOddDenominator_isEquivalent_leading (order : ℕ) :
    halfOddDenominator order ~[atTop]
      halfOddDenominatorLeading order := by
  induction order with
  | zero =>
      apply Filter.EventuallyEq.isEquivalent
      filter_upwards with index
      simp [halfOddDenominator, halfOddDenominatorLeading]
  | succ order ih =>
      have hfactor := besselLinearFactor_isEquivalent order
      have hproduct := ih.mul hfactor
      have hleft :
          halfOddDenominator order *
              (fun index : ℕ =>
                (2 * (index : ℝ)) - (2 * order + 1 : ℕ)) =ᶠ[atTop]
            halfOddDenominator (order + 1) := by
        filter_upwards with index
        rw [Pi.mul_apply, halfOddDenominator_succ]
        push_cast
        rfl
      have hright :
          halfOddDenominatorLeading order *
              (fun index : ℕ => 2 * (index : ℝ)) =ᶠ[atTop]
            halfOddDenominatorLeading (order + 1) := by
        filter_upwards with index
        rw [Pi.mul_apply]
        unfold halfOddDenominatorLeading
        rw [pow_succ]
      exact (hproduct.congr_left hleft).congr_right hright

noncomputable def centralBinomialScaled (index : ℕ) : ℝ :=
  (Nat.centralBinom index : ℝ) / (4 : ℝ) ^ index

noncomputable def centralBinomialScaledLeading (index : ℕ) : ℝ :=
  1 / Real.sqrt (Real.pi * (index : ℝ))

theorem centralBinomialScaled_isEquivalent_leading :
    centralBinomialScaled ~[atTop] centralBinomialScaledLeading := by
  have hfourRefl :
      (fun index : ℕ => (4 : ℝ) ^ index) ~[atTop]
        (fun index : ℕ => (4 : ℝ) ^ index) := IsEquivalent.refl
  have hquotient :=
    IsEquivalent.div centralBinomial_isEquivalent_leading hfourRefl
  change centralBinomialScaled ~[atTop]
    (fun index : ℕ => centralBinomialLeadingTerm index / (4 : ℝ) ^ index)
      at hquotient
  apply hquotient.congr_right
  filter_upwards with index
  unfold centralBinomialLeadingTerm centralBinomialScaledLeading
  have hfour : (4 : ℝ) ^ index ≠ 0 := by positivity
  field_simp [hfour]

noncomputable def halfPowerAmplitude
    (order : ℕ) (scale : ℝ) (index : ℕ) : ℝ :=
  (-1 : ℝ) ^ order * scale ^ index * halfOddNumerator order

noncomputable def halfPowerAsymptoticComparison
    (order : ℕ) (scale : ℝ) (index : ℕ) : ℝ :=
  halfPowerAmplitude order scale index *
      centralBinomialScaledLeading index /
    halfOddDenominatorLeading order index

theorem halfPowerClosedCoefficient_isEquivalent_comparison
    (order : ℕ) (scale : ℝ) :
    halfPowerClosedCoefficient order scale ~[atTop]
      halfPowerAsymptoticComparison order scale := by
  have hcentral := centralBinomialScaled_isEquivalent_leading
  have hdenominator := halfOddDenominator_isEquivalent_leading order
  have hamplitude :
      halfPowerAmplitude order scale ~[atTop]
        halfPowerAmplitude order scale := IsEquivalent.refl
  have hresult := (hamplitude.mul hcentral).div hdenominator
  apply (hresult.congr_left ?_).congr_right
  · filter_upwards with index
    rfl
  · filter_upwards with index
    change halfPowerAmplitude order scale index *
        centralBinomialScaled index / halfOddDenominator order index =
      halfPowerClosedCoefficient order scale index
    unfold halfPowerAmplitude centralBinomialScaled
    unfold halfPowerClosedCoefficient
    ring

noncomputable def halfPowerSingularConstant (order : ℕ) : ℝ :=
  (-1 : ℝ) ^ order * halfOddNumerator order /
    ((2 : ℝ) ^ order * Real.sqrt Real.pi)

noncomputable def halfPowerRpowLeadingCoefficient
    (order : ℕ) (scale : ℝ) (index : ℕ) : ℝ :=
  halfPowerSingularConstant order * scale ^ index *
    (index : ℝ) ^ (-((order : ℝ) + 1 / 2))

theorem halfPowerComparison_eventuallyEq_rpow
    (order : ℕ) (scale : ℝ) :
    halfPowerAsymptoticComparison order scale =ᶠ[atTop]
      halfPowerRpowLeadingCoefficient order scale := by
  filter_upwards [eventually_ne_atTop 0] with index hindex
  have hindexPos : (0 : ℝ) < index := by positivity
  have hindexNonneg : (0 : ℝ) ≤ index := hindexPos.le
  have hpiNonneg : (0 : ℝ) ≤ Real.pi := Real.pi_pos.le
  have hsqrtPi : Real.sqrt Real.pi ≠ 0 := by positivity
  have hsqrtIndex : Real.sqrt (index : ℝ) ≠ 0 := by positivity
  have hindexPow : (index : ℝ) ^ order ≠ 0 := by positivity
  have htwoPow : (2 : ℝ) ^ order ≠ 0 := by positivity
  have hsqrtMul :
      Real.sqrt (Real.pi * (index : ℝ)) =
        Real.sqrt Real.pi * Real.sqrt (index : ℝ) := by
    rw [Real.sqrt_mul hpiNonneg]
  have hrpowAdd :
      (index : ℝ) ^ ((order : ℝ) + 1 / 2) =
        (index : ℝ) ^ (order : ℝ) * (index : ℝ) ^ (1 / 2 : ℝ) :=
    Real.rpow_add hindexPos _ _
  unfold halfPowerAsymptoticComparison halfPowerAmplitude
  unfold centralBinomialScaledLeading halfOddDenominatorLeading
  unfold halfPowerRpowLeadingCoefficient halfPowerSingularConstant
  rw [hsqrtMul, Real.sqrt_eq_rpow]
  rw [Real.rpow_neg hindexNonneg, hrpowAdd, Real.rpow_natCast]
  rw [mul_pow]
  field_simp [hsqrtPi, hsqrtIndex, hindexPow, htwoPow]
  rw [Real.sqrt_eq_rpow]

theorem halfPowerClosedCoefficient_isEquivalent_rpow
    (order : ℕ) (scale : ℝ) :
    halfPowerClosedCoefficient order scale ~[atTop]
      halfPowerRpowLeadingCoefficient order scale :=
  (halfPowerClosedCoefficient_isEquivalent_comparison order scale).trans
    (halfPowerComparison_eventuallyEq_rpow order scale).isEquivalent

end FibonacciRibbonKernel
